package UX;

import cifrado.cifrado_mensaje_des;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
public class cifradoDes extends javax.swing.JFrame {
    cifrado_mensaje_des _DES_mensaje;
    String ruta;

    int valor = 0;
    /**
     * Creates new form cifradoDes
     */
    public cifradoDes() {
        initComponents();
    }//cifradoDes
    
    //coloca todos los elementos en blanco
    protected void limpiar(){
        txtClave_privada.setText("");
        ruta = "";
        valor = 0;
        textAreaMensaje.setText(ruta);
        textAreaMensaje.setEditable(true);
    }//limpiar
    
    
    protected void accionCifrado(){
        String clave = txtClave_privada.getText() ;
        String _mensaje = textAreaMensaje.getText();
        
        if( !_mensaje.equals("") && !clave.equals("") ){

            if( clave.length() > 7 ){
                  // inciamos la clace mensajeCrifado para el cifrado del mensaje
                  mensajeCifrado( _mensaje, clave );
                

            }else{
                 mensaje( "La clave es muy corta, coloca una clave mayor a 7 caracteres" , "Advertencia", 2);
            }

        }else{
            mensaje( "Coloca el mensaje y la clave para cifrar" , "Advertencia", 2);
        }
        
    }//accionCifrado
    
    protected void accionesDecifrado(){
        
        String clave = txtClave_privada.getText() ;
        String _mensaje = textAreaMensaje.getText();
        
        if( !_mensaje.equals("") && !clave.equals("") ){

            if( clave.length() > 7 ){
                  // inciamos la clace mensajeCrifado para el cifrado del mensaje
                  mensajeDesifado( _mensaje, clave );
                

            }else{
                 mensaje( "La clave es muy corta, coloca una clave mayor a 7 caracteres" , "Advertencia", 2);
            }

        }else{
            mensaje( "Coloca el mensaje y la clave para cifrar" , "Advertencia", 2);
        }
        
    }//accionCifrado
    
    protected void mensajeCifrado(String mensaje, String clave){
        
        try {
            // TODO add your handling code here:
            String _clave = txtClave_privada.getText() ;
            String mesnaje_cifrado = _DES_mensaje.cifrar( mensaje, clave);
             
            textAreaMensaje.setText(mesnaje_cifrado);
             
            mensaje("El mensaje se ha cifado", "Mensaje cifrado", 1);
            
            
        } catch (Exception ex) {
            Logger.getLogger(cifradoDes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//mensajeCifrado
    
    protected void mensajeDesifado(String mensaje, String clave){
            
        try {

          textAreaMensaje.setText( _DES_mensaje.descifrar(mensaje, clave)  );
          
        } catch (Exception ex) {
            Logger.getLogger(cifradoDes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//archivoCifrado
    
    //ventana de daialogo para la muestra de mensajes
    protected void mensaje(String _mensaje, String titulo, int tipo){
        JOptionPane.showMessageDialog(null, _mensaje, titulo, tipo);
    }//mensaje

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btn_cifrado = new javax.swing.JButton();
        btn_desifrado = new javax.swing.JButton();
        txtClave_privada = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMensaje = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 36))); // NOI18N

        jLabel1.setText("Clave");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btn_cifrado.setText("Cifrar");
        btn_cifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifradoActionPerformed(evt);
            }
        });

        btn_desifrado.setText("Descifrar");
        btn_desifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desifradoActionPerformed(evt);
            }
        });

        txtClave_privada.setFocusCycleRoot(true);

        jLabel4.setText("Mensaje");

        textAreaMensaje.setColumns(20);
        textAreaMensaje.setLineWrap(true);
        textAreaMensaje.setRows(5);
        textAreaMensaje.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textAreaMensaje);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(txtClave_privada, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_cifrado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_desifrado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave_privada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cifrado)
                    .addComponent(btn_desifrado))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifradoActionPerformed
        accionCifrado();
    }//GEN-LAST:event_btn_cifradoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btn_desifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desifradoActionPerformed
        // TODO add your handling code here:
        accionesDecifrado();
    }//GEN-LAST:event_btn_desifradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cifradoDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cifradoDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cifradoDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cifradoDes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cifradoDes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btn_cifrado;
    private javax.swing.JButton btn_desifrado;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaMensaje;
    private javax.swing.JTextField txtClave_privada;
    // End of variables declaration//GEN-END:variables
}
